# Generated by Django 5.2.6 on 2025-09-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WfClient',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_code', models.IntegerField()),
                ('client_name', models.CharField(max_length=128)),
                ('client_cnpj', models.CharField(max_length=14, unique=True)),
                ('client_adress', models.CharField(max_length=255)),
                ('client_city', models.CharField(max_length=100)),
                ('client_state', models.CharField(default='NN', max_length=2)),
                ('client_state_subscription', models.CharField(blank=True, max_length=14, null=True)),
                ('client_date', models.DateField(blank=True, null=True)),
                ('client_is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'wf_client',
            },
        ),
    ]
