# Generated by Django 5.2.6 on 2025-09-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=5, unique=True)),
                ('product_descrption', models.CharField(blank=True, max_length=255, null=True)),
                ('product_group', models.CharField(blank=True, max_length=32, null=True)),
                ('product_brand', models.CharField(blank=True, max_length=32, null=True)),
                ('product_value', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'wf_products',
            },
        ),
    ]
