# Generated by Django 5.2.6 on 2025-09-17 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UF',
            fields=[
                ('uf_id', models.AutoField(primary_key=True, serialize=False)),
                ('uf_name', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='wfclient',
            name='client_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_uf', to='wefixhub.uf'),
        ),
    ]
