# Generated by Django 5.2.6 on 2025-09-18 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_descrption',
            new_name='product_description',
        ),
    ]
