# Generated by Django 5.2.6 on 2025-09-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0002_alter_wfclient_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wfclient',
            name='id',
        ),
        migrations.AddField(
            model_name='wfclient',
            name='client_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
