# Generated by Django 5.2.6 on 2025-09-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0003_remove_wfclient_id_wfclient_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfclient',
            name='client_code',
            field=models.IntegerField(),
        ),
    ]
