# Generated by Django 5.2.6 on 2025-09-21 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0004_wfclient_user_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENTREGUE', 'Entregue')], default='PENDENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='PedidoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ENVIO', 'Em Envio'), ('ENTREGUE', 'Entregue')], default='PENDENTE', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='wefixhub.wfclient')),
            ],
        ),
    ]
