# Generated by Django 5.2.6 on 2025-09-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0005_product_status_pedidostatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ENVIO', 'Em Envio'), ('ENTREGUE', 'Entregue')], default='PENDENTE', max_length=20),
        ),
    ]
