# Generated by Django 5.2.6 on 2025-09-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0006_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_envio_solicitada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
