# Generated by Django 5.2.6 on 2025-09-22 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0007_pedido_data_envio_solicitada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wfclient',
            name='client_adress',
        ),
        migrations.AlterField(
            model_name='pedidostatus',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('SOLICITADO', 'Solicitado'), ('EM_ENVIO', 'Em Envio'), ('ENTREGUE', 'Entregue')], default='PENDENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('is_default', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='wefixhub.wfclient')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enderecos', to='wefixhub.wefixhub_uf')),
            ],
        ),
    ]
