# Generated by Django 5.2.6 on 2025-09-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0008_remove_wfclient_client_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfclient',
            name='client_adress',
            field=models.CharField(default='PENDENTE', max_length=255),
            preserve_default=False,
        ),
    ]
