# Generated by Django 5.2.6 on 2025-09-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0011_alter_pedido_cliente_alter_pedido_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_value',
        ),
        migrations.AddField(
            model_name='product',
            name='product_value_es',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_value_sp',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
