# Generated by Django 5.2.6 on 2025-09-25 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0013_alter_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='valor_unitario_es',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='valor_unitario_sp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_do_pedido', to='wefixhub.product'),
        ),
    ]
