# Generated by Django 5.2.6 on 2025-09-25 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0014_itempedido_valor_unitario_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_product',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 9, 25)),
            preserve_default=False,
        ),
    ]
