# Generated by Django 5.2.6 on 2025-09-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0015_product_date_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='frete_option',
            field=models.CharField(blank=True, choices=[('SEDEX', 'Sedex'), ('CORREIOS', 'Correios'), ('ONIBUS', 'Ônibus'), ('TRANSPORTADORA', 'Transportadora')], default='CORREIOS', max_length=20, null=True),
        ),
    ]
