# Generated by Django 5.2.6 on 2025-09-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0016_pedido_frete_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nota_fiscal',
            field=models.CharField(blank=True, choices=[('COM', 'Com Nota Fiscal'), ('SEM', 'Sem Nota Fiscal')], default='SEM', max_length=3, null=True),
        ),
    ]
