# Generated by Django 5.2.6 on 2025-10-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0017_pedido_nota_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfclient',
            name='client_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
