# Generated by Django 5.2.6 on 2025-10-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0018_alter_wfclient_client_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfclient',
            name='frete_preferencia',
            field=models.CharField(blank=True, choices=[('SEDEX', 'Sedex'), ('CORREIOS', 'Correios'), ('ONIBUS', 'Ônibus'), ('TRANSPORTADORA', 'Transportadora')], default='CORREIOS', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wfclient',
            name='nota_fiscal_preferencia',
            field=models.CharField(blank=True, choices=[('COM', 'Com Nota Fiscal'), ('SEM', 'Sem Nota Fiscal')], default='SEM', max_length=3, null=True),
        ),
    ]
