# Generated by Django 5.2.6 on 2025-10-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0019_wfclient_frete_preferencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='frete_option',
            field=models.CharField(blank=True, choices=[('SEDEX', 'Sedex'), ('CORREIOS', 'Correios'), ('ONIBUS', 'Ônibus'), ('TRANSPORTADORA', 'Transportadora'), ('RETIRADA', 'Retirada')], default='CORREIOS', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wfclient',
            name='frete_preferencia',
            field=models.CharField(blank=True, choices=[('SEDEX', 'Sedex'), ('CORREIOS', 'Correios'), ('ONIBUS', 'Ônibus'), ('TRANSPORTADORA', 'Transportadora'), ('RETIRADA', 'Retirada')], default='CORREIOS', max_length=20, null=True),
        ),
    ]
