# Generated by Django 5.2.6 on 2025-10-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0020_alter_pedido_frete_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='orcamento_pdf',
            field=models.FileField(blank=True, null=True, upload_to='orcamentos/'),
        ),
    ]
