# Generated by Django 5.2.6 on 2025-10-03 22:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0021_pedido_orcamento_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
