# Generated by Django 5.2.6 on 2025-10-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0024_pedido_criado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='valor_unitario',
        ),
    ]
