# Generated by Django 5.2.6 on 2025-10-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0025_remove_itempedido_valor_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENTREGUE', 'Entregue'), ('EM_ENVIO', 'Em Envio'), ('PENDENTE', 'Pendente'), ('ORCAMENTO', 'Orçamento'), ('FINANCEIRO', 'Analise De Credito'), ('SEPARACAO', 'Separação'), ('EXPEDICAO', 'Expedição'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidostatus',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENTREGUE', 'Entregue'), ('EM_ENVIO', 'Em Envio'), ('PENDENTE', 'Pendente'), ('ORCAMENTO', 'Orçamento'), ('FINANCEIRO', 'Analise De Credito'), ('SEPARACAO', 'Separação'), ('EXPEDICAO', 'Expedição'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=20),
        ),
    ]


from django.db import migrations, models

def migrate_status_data(apps, schema_editor):
    # Obtém o modelo Pedido do estado atual do projeto
    Pedido = apps.get_model('wefixhub', 'Pedido')

    # Mapeamento dos status antigos para os novos
    status_map = {
        'ENTREGUE': 'FINALIZADO',
        'EM_ENVIO': 'EXPEDICAO',
        # Se você tinha 'CONCLUIDO', adicione aqui
        'CONCLUIDO': 'FINALIZADO',
        # Se você tinha 'SOLICITADO', adicione aqui
        'SOLICITADO': 'ORCAMENTO',
    }

    # Itera sobre o mapa e atualiza os pedidos
    for old_status, new_status in status_map.items():
        Pedido.objects.filter(status=old_status).update(status=new_status)

class Migration(migrations.Migration):

    dependencies = [
        # Substitua com o nome da sua migração anterior
        ('wefixhub', '0025_remove_itempedido_valor_unitario'),
    ]

    operations = [
        # Primeiro, executa a migração de dados
        migrations.RunPython(migrate_status_data),

        # Depois, altera o campo 'status' para usar a nova tupla de choices
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('PENDENTE', 'Pendente'),
                    ('ORCAMENTO', 'Orçamento'),
                    ('FINANCEIRO', 'Analise De Credito'),
                    ('SEPARACAO', 'Separação'),
                    ('EXPEDICAO', 'Expedição'),
                    ('FINALIZADO', 'Finalizado'),
                ],
                default='PENDENTE'
            ),
        ),
    ]