# Generated by Django 5.2.6 on 2025-10-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0027_alter_pedido_status_alter_pedidostatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENTREGUE', 'Entregue'), ('EM_ENVIO', 'Em Envio'), ('ORCAMENTO', 'Orçamento'), ('FINANCEIRO', 'Analise De Credito'), ('SEPARACAO', 'Separação'), ('EXPEDICAO', 'Expedição'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidostatus',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENTREGUE', 'Entregue'), ('EM_ENVIO', 'Em Envio'), ('ORCAMENTO', 'Orçamento'), ('FINANCEIRO', 'Analise De Credito'), ('SEPARACAO', 'Separação'), ('EXPEDICAO', 'Expedição'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=20),
        ),
    ]
