# Generated by Django 5.2.6 on 2025-10-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0028_alter_pedido_status_alter_pedidostatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfclient',
            name='client_code',
            field=models.IntegerField(unique=True),
        ),
    ]
