# Generated by Django 5.2.6 on 2025-10-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0030_alter_pedido_status_alter_pedidostatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
