# Generated by Django 5.2.6 on 2025-10-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0031_pedido_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfclient',
            name='observacao_preferencia',
            field=models.TextField(blank=True, null=True, verbose_name='Observação Padrão'),
        ),
    ]
