# Generated by Django 5.2.6 on 2025-10-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0032_wfclient_observacao_preferencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedidoStatus',
        ),
    ]
