# Generated by Django 5.2.6 on 2025-10-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0034_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENTREGUE', 'Entregue'), ('EM_ENVIO', 'Em Envio'), ('ORCAMENTO', 'Orçamento'), ('FINANCEIRO', 'Analise De Credito'), ('SEPARACAO', 'Separação'), ('EXPEDICAO', 'Expedição'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('ATRASADO', 'Atrasado'), ('RASCUNHO', 'Rascunho')], default='PENDENTE', max_length=20),
        ),
    ]
