# Generated by Django 5.2.6 on 2025-11-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0035_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='erros_upload',
            field=models.TextField(blank=True, null=True, verbose_name='Erros de Upload da Planilha'),
        ),
    ]
