# Generated by Django 5.2.6 on 2026-01-25 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0036_pedido_erros_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedidoIgnorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_tentativa', models.DateTimeField(auto_now_add=True)),
                ('codigo_produto', models.CharField(max_length=50)),
                ('descricao_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade_tentada', models.IntegerField(null=True)),
                ('motivo_erro', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wefixhub.wfclient')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_ignorados', to='wefixhub.pedido')),
            ],
            options={
                'verbose_name': 'Item Ignorado',
                'verbose_name_plural': 'Itens Ignorados',
                'db_table': 'wf_itens_ignorados',
            },
        ),
    ]
