# Generated by Django 5.2.6 on 2026-03-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0037_itempedidoignorado'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emissao', models.DateField(db_index=True, verbose_name='Emissão')),
                ('Codigo_Cliente', models.IntegerField(verbose_name='Código Cliente')),
                ('Pedido', models.CharField(max_length=50, verbose_name='Pedido')),
                ('Produto_Codigo', models.CharField(max_length=50, verbose_name='Código do Produto')),
                ('Produto_Descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('Quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('Unitario', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Unitário')),
                ('Total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Item')),
                ('cliente_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wf_vendas_reais',
                'unique_together': {('Emissao', 'Codigo_Cliente', 'Pedido', 'Produto_Codigo')},
            },
        ),
    ]
