# Generated by Django 5.2.6 on 2026-03-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0038_vendareal'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPedidoERP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emissao', models.DateField(verbose_name='Data de Emissão')),
                ('numero_pedido', models.CharField(db_index=True, max_length=50, verbose_name='Número do Pedido')),
                ('cod_cliente', models.CharField(max_length=20, verbose_name='Cód. Cliente')),
                ('nome_cliente', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('situacao', models.CharField(max_length=100, verbose_name='Situação/Status')),
                ('expedido', models.BooleanField(default=False, verbose_name='Expedido?')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
            ],
            options={
                'verbose_name': 'Status Pedido ERP',
                'verbose_name_plural': 'Status Pedidos ERP',
                'db_table': 'wf_status_pedidos_erp',
                'ordering': ['-data_importacao', '-numero_pedido'],
            },
        ),
    ]
