# Generated by Django 5.2.6 on 2026-03-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0039_statuspedidoerp'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidoignorado',
            name='notificado',
            field=models.BooleanField(default=False, verbose_name='Cliente Avisado?'),
        ),
    ]
