# Generated by Django 5.2.6 on 2026-03-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0041_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidoignorado',
            name='data_notificacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Aviso'),
        ),
    ]
