# Generated by Django 5.2.6 on 2026-03-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0042_itempedidoignorado_data_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidoignorado',
            name='lote_notificacao',
            field=models.CharField(blank=True, help_text='ID único do lote de envio no WhatsApp', max_length=20, null=True),
        ),
    ]
