# Generated by Django 5.2.6 on 2026-03-20 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0043_itempedidoignorado_lote_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugestaoCompraERP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_codigo', models.CharField(db_index=True, max_length=50)),
                ('produto_descricao', models.CharField(max_length=255)),
                ('giro_diario', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Giro (Unidades/Dia)')),
                ('intervalo_medio_dias', models.IntegerField(verbose_name='Média de dias entre compras')),
                ('ultima_compra', models.DateField()),
                ('quantidade_sugerida', models.IntegerField()),
                ('data_calculo', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes_giro', to='wefixhub.wfclient')),
            ],
            options={
                'verbose_name': 'Sugestão de Compra ERP',
                'verbose_name_plural': 'Sugestões de Compra ERP',
                'db_table': 'wf_sugestao_compra_erp',
            },
        ),
    ]
