# Generated by Django 5.2.6 on 2026-03-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0044_sugestaocompraerp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status_estoque',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('SEM_ESTOQUE', 'Sem Estoque')], default='DISPONIVEL', max_length=20),
        ),
    ]
