# Generated by Django 5.2.6 on 2026-03-21 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0045_product_status_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedidoignorado',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_ignorados', to='wefixhub.pedido'),
        ),
    ]
