# Generated by Django 5.2.6 on 2026-03-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0046_alter_itempedidoignorado_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_index=True, max_length=20)),
                ('product_description', models.CharField(blank=True, max_length=255, null=True)),
                ('product_value_sp', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('product_value_es', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('status_estoque', models.CharField(default='DISPONIVEL', max_length=20)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Histórico de Preços',
                'db_table': 'wf_historico_precos',
                'ordering': ['-data_registro'],
            },
        ),
    ]
