# Generated by Django 5.2.6 on 2026-03-21 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0047_historicopreco'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
