# Generated by Django 5.2.6 on 2026-03-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0048_product_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugestaocompraerp',
            name='score_relevancia',
            field=models.IntegerField(default=0, verbose_name='Score de Relevância (0-100)'),
        ),
    ]
