# Generated by Django 5.2.6 on 2026-03-23 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0049_add_score_relevancia_sugestao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome da Empresa')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Identificador único')),
                ('plano', models.CharField(choices=[('FREE', 'Gratuito'), ('BASICO', 'Básico'), ('PRO', 'Profissional')], default='FREE', max_length=10, verbose_name='Plano')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contato')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'wf_empresa',
            },
        ),
        migrations.AddField(
            model_name='historicopreco',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='wefixhub.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='wefixhub.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='product',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='wefixhub.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='statuspedidoerp',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_erp', to='wefixhub.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='vendareal',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas_reais', to='wefixhub.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='wfclient',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='wefixhub.empresa', verbose_name='Empresa'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('ADMIN', 'Administrador'), ('VENDEDOR', 'Vendedor')], default='ADMIN', max_length=10, verbose_name='Papel')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='wefixhub.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'db_table': 'wf_perfil_usuario',
            },
        ),
    ]
