# Generated by Django 5.2.6 on 2026-03-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0050_empresa_historicopreco_empresa_pedido_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfclient',
            name='client_cnpj',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='wfclient',
            name='client_code',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='wfclient',
            unique_together={('empresa', 'client_cnpj'), ('empresa', 'client_code')},
        ),
    ]
