# Generated by Django 5.2.6 on 2026-03-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0052_empresa_expira_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('empresa', 'product_code')},
        ),
    ]
