# Generated by Django 5.2.6 on 2026-03-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0053_alter_product_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
