# Generated by Django 5.2.6 on 2026-03-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0054_empresa_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='acesso_permanente',
            field=models.BooleanField(default=False, verbose_name='Acesso permanente'),
        ),
    ]
