# Generated by Django 5.2.6 on 2026-03-25 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0060_comentariopedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadetarefa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comentariopedido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificacaopedido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AnexoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='tarefas/anexos/')),
                ('nome', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='wefixhub.tarefa')),
            ],
            options={
                'verbose_name': 'Anexo de Tarefa',
                'verbose_name_plural': 'Anexos de Tarefas',
                'db_table': 'wf_anexo_tarefa',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('PEDIDO_CRIADO', 'Pedido criado'), ('PEDIDO_FINALIZADO', 'Pedido finalizado'), ('TAREFA_CRIADA', 'Tarefa criada'), ('TAREFA_EDITADA', 'Tarefa editada'), ('TAREFA_EXCLUIDA', 'Tarefa excluída'), ('ANEXO_UPLOAD', 'Anexo enviado'), ('ANEXO_EXCLUIDO', 'Anexo excluído'), ('ORCAMENTO_UPLOAD', 'Orçamento enviado'), ('STATUS_ALTERADO', 'Status alterado')], max_length=30)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wefixhub.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'wf_log_auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
