# Generated by Django 5.2.6 on 2026-03-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0062_foto_perfil_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/'),
        ),
    ]
