# Generated by Django 5.2.6 on 2026-03-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0063_foto_perfil_membro'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfclient',
            name='client_cep',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='wfclient',
            name='client_adress',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wfclient',
            name='client_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
