# Generated by Django 5.2.6 on 2026-03-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0064_wfclient_client_cep_alter_wfclient_client_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidoignorado',
            name='descartado_pelo_cliente',
            field=models.BooleanField(default=False, verbose_name='Descartado pelo cliente'),
        ),
    ]
