# Generated by Django 5.2.6 on 2026-03-28 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefixhub', '0065_itempedidoignorado_descartado_pelo_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotRFM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ref', models.DateField(help_text='Sempre o dia 1 do mês de referência', verbose_name='Referência (1º do mês)')),
                ('cod_cliente', models.IntegerField(verbose_name='Código do Cliente')),
                ('nome_cliente', models.CharField(max_length=255)),
                ('segmento', models.CharField(choices=[('Campeão', 'Campeão'), ('Fiel', 'Fiel'), ('Potencial', 'Potencial'), ('Em Risco', 'Em Risco'), ('Adormecido', 'Adormecido')], max_length=20)),
                ('r_score', models.PositiveSmallIntegerField()),
                ('f_score', models.PositiveSmallIntegerField()),
                ('m_score', models.PositiveSmallIntegerField()),
                ('rfm_score', models.PositiveSmallIntegerField()),
                ('recencia', models.IntegerField(verbose_name='Recência (dias)')),
                ('frequencia', models.IntegerField()),
                ('monetario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_rfm', to='wefixhub.empresa')),
            ],
            options={
                'verbose_name': 'Snapshot RFM',
                'verbose_name_plural': 'Snapshots RFM',
                'db_table': 'wf_snapshot_rfm',
                'ordering': ['-data_ref', 'cod_cliente'],
                'unique_together': {('empresa', 'data_ref', 'cod_cliente')},
            },
        ),
    ]
