"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import pymysql
from decouple import config, Csv
import dj_database_url
import os

# Inicializa o pymysql para que o Django o use como driver do MySQL
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================================================================
# CONFIGURAÇÕES DE SEGURANÇA E CORE
# ==============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Hosts permitidos (carregados do .env)
# Atenção: Em produção (Railway), esta variável DEVE incluir o domínio público.
ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())

# Origens confiáveis para requisições CSRF (essencial para segurança)
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())


# ==============================================================================
# APLICAÇÕES E MIDDLEWARE
# ==============================================================================

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_htmx',
    'django.contrib.humanize',
    'storages',
    # Seus aplicativos personalizados
    'wefixhub',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise deve vir logo após o SecurityMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'wefixhub.middleware.EmpresaMiddleware',
]


# ==============================================================================
# CONFIGURAÇÕES DE URL E TEMPLATES
# ==============================================================================

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Pasta de templates na raiz do projeto
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'wefixhub.context_processors.carrinho_count',
                'wefixhub.context_processors.notif_tarefas_count',
                'wefixhub.context_processors.notif_pedidos_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# ==============================================================================
# BANCO DE DADOS (CORREÇÃO DE CONEXÃO EM PRODUÇÃO)
# ==============================================================================

# PRIORIDADE 1: Tenta ler a variável injetada pelo ambiente (Railway)
DATABASE_URL_VALUE = os.environ.get('DATABASE_URL')

if DATABASE_URL_VALUE:
    # MODO PRODUÇÃO: Usa a URL injetada pelo Railway (CORRETO)
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL_VALUE, 
            conn_max_age=0,
            # Removido 'ssl_require=False' para deixar o dj-database-url ser mais robusto
        )
    }
else:
    # MODO DESENVOLVIMENTO: Fallback para configurações locais se DATABASE_URL não for definida.
    # Este bloco era o que estava causando o erro 500 no Railway.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('MYSQLDATABASE'),
            'USER': config('MYSQLUSER'),
            'PASSWORD': config('MYSQLPASSWORD'),
            'HOST': config('MYSQLHOST'),
            'PORT': config('MYSQLPORT', cast=int),
        }
    }


# ==============================================================================
# VALIDAÇÃO DE SENHAS
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ==============================================================================
# INTERNACIONALIZAÇÃO
# ==============================================================================

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True


# ==============================================================================
# ARQUIVOS ESTÁTICOS E DE MÍDIA
# ==============================================================================

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Diretórios onde o Django procura por arquivos estáticos (além das pastas de apps).
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Diretório para onde o `collectstatic` irá copiar os arquivos para produção.
STATIC_ROOT = BASE_DIR / 'staticfiles_collect'

# Armazenamento otimizado do WhiteNoise para produção.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ==============================================================================
# MEDIA — Cloudflare R2 em produção, disco local em desenvolvimento
# ==============================================================================
R2_ACCESS_KEY_ID     = config('R2_ACCESS_KEY_ID', default=None)
R2_SECRET_ACCESS_KEY = config('R2_SECRET_ACCESS_KEY', default=None)
R2_BUCKET_NAME       = config('R2_BUCKET_NAME', default=None)
R2_ACCOUNT_ID        = config('R2_ACCOUNT_ID', default=None)
R2_PUBLIC_URL        = config('R2_PUBLIC_URL', default=None)

if R2_ACCESS_KEY_ID:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    AWS_ACCESS_KEY_ID       = R2_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY   = R2_SECRET_ACCESS_KEY
    AWS_STORAGE_BUCKET_NAME = R2_BUCKET_NAME
    AWS_S3_ENDPOINT_URL     = f"https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
    AWS_S3_REGION_NAME      = 'auto'
    AWS_DEFAULT_ACL         = None
    AWS_S3_FILE_OVERWRITE   = False
    AWS_QUERYSTRING_AUTH    = False
    # Faz o django-storages gerar URLs usando o domínio público do R2
    AWS_S3_CUSTOM_DOMAIN    = R2_PUBLIC_URL.replace('https://', '')
    MEDIA_URL = R2_PUBLIC_URL + '/'
else:
    MEDIA_URL  = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# settings.py
SESSION_COOKIE_AGE = 2592000  # Mantém a sessão viva por 30 dias (em segundos)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False # Garante que não apaga ao fechar a aba

# ==============================================================================
# OUTRAS CONFIGURAÇÕES
# ==============================================================================

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurações de redirecionamento de login/logout
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/accounts/login/'


# ==============================================================================
# STRIPE
# ==============================================================================
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')
STRIPE_PRICE_BASICO = config('STRIPE_PRICE_BASICO', default='')
